---
- hosts: servers
  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - htop
          - 7zip
          - ccze
          - net-tools
          - mc
          - ifupdown
          - resolvconf
          - curl
          - git
    - name: (01) RmDir
      command: rm -rf /tmp/netplan
    - name: (02) Mkdir
      command: mkdir /tmp/netplan
    - name: (03) Download netlan script
      command: wget -P /tmp/netplan/ https://raw.githubusercontent.com/spd-it/Ansible-Playbook-Linux/main/netplan.sh 
    - name: (04) Change permissions
      command: chmod +x /tmp/netplan/netplan.sh
    - name: (05) Remove Netplan
      command: /tmp/netplan/./netplan.sh
